parameters:
#    axoloth_immo.example.class: Axoloth\ImmoBundle\Example

services:
#    axoloth_immo.example:
#        class: %axoloth_immo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
